weights: yolov5s.pt
cfg: ./models/yolo_gun.yaml
data: ./data/gun.yaml
hyp: data/hyp.scratch.yaml
epochs: 10
batch_size: 8
img_size:
- 640
- 640
rect: false
resume: false
nosave: true
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 8
project: runs/train
name: detect_gun
exist_ok: false
total_batch_size: 8
world_size: 1
global_rank: -1
save_dir: runs/train/detect_gun
