wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
adam:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 1
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
cfg:
  desc: null
  value: ''
data:
  desc: null
  value: data/gun.yaml
device:
  desc: null
  value: '0'
epochs:
  desc: null
  value: 10
evolve:
  desc: null
  value: false
exist_ok:
  desc: null
  value: 1
global_rank:
  desc: null
  value: -1
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
img_size:
  desc: null
  value:
  - 640
  - 640
local_rank:
  desc: null
  value: -1
log_artifacts:
  desc: null
  value: false
log_imgs:
  desc: null
  value: 16
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: gun
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
project:
  desc: null
  value: runs/train
rect:
  desc: null
  value: false
resume:
  desc: null
  value: true
save_dir:
  desc: null
  value: runs/train/gun
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
total_batch_size:
  desc: null
  value: 1
weights:
  desc: null
  value: ./runs/train/gun_backup/weights/last.pt
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: 1
